version: "3.9"

services:
  api:
    env_file:
      - .env
    volumes:
      - ./apps/api:/app/apps/api
      - ./node_modules:/app/node_modules
    ports:
      - "4000:4000"

  web:
    env_file:
      - .env
    volumes:
      - ./apps/web:/app/apps/web
      - ./node_modules:/app/node_modules
    ports:
      - "3000:3000"
